# Generated by Django 5.0.6 on 2024-08-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JMP_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstname',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastname',
        ),
    ]
