# Generated by Django 5.0.6 on 2024-08-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JMP_App', '0002_rename_firstname_account_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
