# Generated by Django 5.0.6 on 2024-08-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JMP_App', '0003_alter_account_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('icon', models.URLField(verbose_name='File Url')),
                ('price', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, max_length=75, null=True)),
            ],
        ),
    ]
