# Generated by Django 5.0.6 on 2024-08-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JMP_App', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
