# Generated by Django 5.0.6 on 2024-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JMP_App', '0005_services_icon_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=950, null=True)),
                ('project_picture', models.URLField(verbose_name='File Url')),
                ('project_picture_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, max_length=75, null=True)),
            ],
        ),
    ]
